import { status } from '@grpc/grpc-js';

export const GRPC_EXCEPTION_ERROR_CODES: Record<
  string,
  (typeof status)[keyof typeof status]
> = {
  ['ERR_BAD_REQUEST']: status.INVALID_ARGUMENT,
  ['ERR_UNAUTHORIZED']: status.UNAUTHENTICATED,
  ['ERR_FORBIDDEN']: status.PERMISSION_DENIED,
  ['ERR_NOT_FOUND']: status.NOT_FOUND,
  ['ERR_CONFLICT']: status.ALREADY_EXISTS,
  ['ERR_GONE']: status.ABORTED,
  ['ERR_TOO_MANY_REQUESTS']: status.RESOURCE_EXHAUSTED,
  ['ERR_CLIENT_CLOSED_REQUEST']: status.CANCELLED,
  ['ERR_INTERNAL_SERVER_ERROR']: status.INTERNAL,
  ['ERR_NOT_IMPLEMENTED']: status.UNIMPLEMENTED,
  ['ERR_BAD_GATEWAY']: status.UNKNOWN,
  ['ERR_SERVICE_UNAVAILABLE']: status.UNAVAILABLE,
  ['ERR_GATEWAY_TIMEOUT']: status.DEADLINE_EXCEEDED,
  ['ERR_HTTP_VERSION_NOT_SUPPORTED']: status.UNAVAILABLE,
  ['ERR_PAYLOAD_TOO_LARGE']: status.OUT_OF_RANGE,
  ['ERR_UNSUPPORTED_MEDIA_TYPE']: status.INVALID_ARGUMENT,
  ['ERR_UNPROCESSABLE_ENTITY']: status.INVALID_ARGUMENT,
  ['ERR_IM_A_TEAPOT']: status.UNKNOWN,
  ['ERR_METHOD_NOT_ALLOWED']: status.UNIMPLEMENTED,
  ['ERR_PRECONDITION_FAILED']: status.FAILED_PRECONDITION,
};
