import {
  BadGatewayException,
  ConflictException,
  ForbiddenException,
  GatewayTimeoutException,
  GoneException,
  HttpVersionNotSupportedException,
  ImATeapotException,
  InternalServerErrorException,
  MethodNotAllowedException,
  NotAcceptableException,
  NotFoundException,
  NotImplementedException,
  PayloadTooLargeException,
  PreconditionFailedException,
  RequestTimeoutException,
  ServiceUnavailableException,
  UnauthorizedException,
  UnprocessableEntityException,
  UnsupportedMediaTypeException,
} from '@nestjs/common';

export const HTTP_EXCEPTION_ERROR_CODES: Record<string, string> = {
  [UnauthorizedException.name]: 'ERR_UNAUTHORIZED',
  [NotFoundException.name]: 'ERR_NOT_FOUND',
  [ForbiddenException.name]: 'ERR_FORBIDDEN',
  [NotAcceptableException.name]: 'ERR_NOT_ACCEPTABLE',
  [RequestTimeoutException.name]: 'ERR_REQUEST_TIMEOUT',
  [ConflictException.name]: 'ERR_CONFLICT',
  [GoneException.name]: 'ERR_GONE',
  [HttpVersionNotSupportedException.name]: 'ERR_HTTP_VERSION_NOT_SUPPORTED',
  [PayloadTooLargeException.name]: 'ERR_PAYLOAD_TOO_LARGE',
  [UnsupportedMediaTypeException.name]: 'ERR_UNSUPPORTED_MEDIA_TYPE',
  [UnprocessableEntityException.name]: 'ERR_UNPROCESSABLE_ENTITY',
  [InternalServerErrorException.name]: 'ERR_INTERNAL_SERVER_ERROR',
  [NotImplementedException.name]: 'ERR_NOT_IMPLEMENTED',
  [ImATeapotException.name]: 'ERR_IM_A_TEAPOT',
  [MethodNotAllowedException.name]: 'ERR_METHOD_NOT_ALLOWED',
  [BadGatewayException.name]: 'ERR_BAD_GATEWAY',
  [ServiceUnavailableException.name]: 'ERR_SERVICE_UNAVAILABLE',
  [GatewayTimeoutException.name]: 'ERR_GATEWAY_TIMEOUT',
  [PreconditionFailedException.name]: 'ERR_PRECONDITION_FAILED',
};
